// Persistence tranche — the files the core writes that are NOT settings.json or
// a layout file, replayed against the C# oracle
// (tests/goldens/persist_csharp.txt, generated by `csharp_probe persist`):
//
//   Tokens.dat                  JsonStorage<byte[]> inside EncryptUtil (DPAPI)
//   AppRules.json               JsonStorage<List<ApplicationRulesModel>>
//   MusicAppExclusionRules.json JsonStorage<List<AppMusicExclusionRuleModel>>
//
// What the oracle can and cannot pin is the whole point of this fixture:
//
//   * The DPAPI blob is deliberately NON-deterministic — it carries a random
//     key and salt — so Tokens.dat can never be byte-compared between the two
//     implementations. Comparing the bytes would be a test that can only ever
//     fail.
//   * What IS deterministic, and therefore what the golden records, is: the
//     wrapper shape (a JSON *string* of base64 — `jsonstorage.bytes`), the
//     plaintext that gets encrypted (Newtonsoft's exact serialization of
//     TokensModel), and the two plain-JSON rule files byte for byte.
//   * The round trip through the port's own DPAPI path is then asserted
//     against the same golden, which is what proves the port's Protect/Unprotect
//     pair is self-consistent and the entropy is right.
//
// A port that "helpfully" wrote Tokens.dat as plain JSON would leave the user's
// access token in cleartext on disk; the `quoted-string` line is the guard.
//
// The theme half of the fixture (`theme.json`) is the last JsonStorage<T> type
// the app persists. It pins two things that a hand-written port gets wrong:
// `IsEditable` is [JsonIgnore] and must NOT be serialized, and the C# copy
// constructor does not carry AppVersion over — so an installed theme records the
// host app's version, not the source model's.

#include <catch2/catch_test_macros.hpp>

#include <windows.h>

#include <lively/common/base64.h>
#include <lively/common/constants.h>
#include <lively/common/encrypt_util.h>
#include <lively/common/json_util.h>
#include <lively/common/path_util.h>
#include <lively/gallery/json_token_store.h>
#include <lively/common/factories/app_theme_factory.h>
#include <lively/models/application_rules.h>
#include <lively/models/gallery.h>
#include <lively/models/settings_model.h>
#include <lively/models/theme.h>

#include <filesystem>
#include <fstream>
#include <optional>
#include <sstream>
#include <string>
#include <vector>

using namespace lively;

namespace {

namespace fs = std::filesystem;

#ifdef LIVELY_GOLDENS_DIR
const std::string kGoldensDir = LIVELY_GOLDENS_DIR;
#else
const std::string kGoldensDir = "tests/goldens";
#endif

std::string read_file(const std::string& path) {
    std::ifstream in(path, std::ios::binary);
    if (!in) return {};
    std::stringstream ss;
    ss << in.rdbuf();
    return ss.str();
}

// The oracle writes `key<TAB>value` lines; the value is already escaped, so a
// raw string compare against its counterpart is the whole assertion.
std::string golden_value(const std::string& key) {
    const std::string text = read_file(kGoldensDir + "/persist_csharp.txt");
    REQUIRE_FALSE(text.empty());
    std::size_t pos = 0;
    while (pos < text.size()) {
        std::size_t end = text.find('\n', pos);
        if (end == std::string::npos) end = text.size();
        std::string line = text.substr(pos, end - pos);
        if (!line.empty() && line.back() == '\r') line.pop_back();
        const std::size_t tab = line.find('\t');
        if (tab != std::string::npos && line.substr(0, tab) == key) {
            return line.substr(tab + 1);
        }
        pos = end + 1;
    }
    return {};
}

// The oracle's own escaping of a raw payload (Probe.Escaped): backslash, the
// C# control escapes, and \xNN below 0x20. Used to build the same canonical
// line the golden holds so the comparison stays byte-exact.
std::string escaped(const std::string& payload) {
    static const char* kHex = "0123456789abcdef";
    std::string out;
    for (const char c : payload) {
        switch (c) {
            case '\\': out += "\\\\"; break;
            case '\n': out += "\\n"; break;
            case '\r': out += "\\r"; break;
            case '\t': out += "\\t"; break;
            case '"': out += "\\\""; break;
            default:
                if (static_cast<unsigned char>(c) < 0x20) {
                    out += "\\x";
                    out += kHex[(static_cast<unsigned char>(c) >> 4) & 0xF];
                    out += kHex[static_cast<unsigned char>(c) & 0xF];
                } else {
                    out += c;
                }
                break;
        }
    }
    return out;
}

std::string hex(const std::vector<unsigned char>& data) {
    static const char* kHex = "0123456789abcdef";
    std::string out;
    out.reserve(data.size() * 2);
    for (const unsigned char b : data) {
        out += kHex[(b >> 4) & 0xF];
        out += kHex[b & 0xF];
    }
    return out;
}

// A scratch file per test, under %TEMP% (matches how the C# probe writes its
// fixtures). Created lazily so each call site names only the file it needs.
std::string write_temp_file(const std::string& name) {
    char buffer[MAX_PATH] = {0};
    REQUIRE(GetTempPathA(MAX_PATH, buffer) != 0);
    const std::string dir = std::string(buffer) + "lively_persist_test\\";
    CreateDirectoryA(dir.c_str(), nullptr);
    return dir + name;
}

// Mirrors Probe.Describe: the oracle renders Expiration with the custom format
// "yyyy-MM-ddTHH:mm:ss.fffffffZ".
//
// Subtle and worth stating: in a .NET *custom* format string `Z` is not a
// recognized specifier (only K, z, zz, zzz relate to the zone), so it is emitted
// LITERALLY — always, whatever the DateTime's Kind is. That is why the oracle
// prints a trailing "Z" even for the MinValue token store, whose stored JSON is
// "0001-01-01T00:00:00" with no zone at all. The port must not "correct" this by
// deriving the suffix from the value.
std::string describe_tokens(const models::gallery::TokensModel& tokens) {
    const auto or_null = [](const std::optional<std::string>& v) {
        return v ? *v : std::string("<null>");
    };

    std::string iso = tokens.expiration_iso;
    if (!iso.empty() && (iso.back() == 'Z' || iso.back() == 'z')) iso.pop_back();

    std::string fraction;
    const std::size_t dot = iso.find('.');
    if (dot != std::string::npos) {
        fraction = iso.substr(dot + 1);
        iso.erase(dot);
    }
    while (fraction.size() < 7) fraction += '0';
    if (fraction.size() > 7) fraction.erase(7);

    return "access=" + or_null(tokens.access_token) + ";refresh=" + or_null(tokens.refresh_token) +
           ";provider=" + or_null(tokens.provider) + ";expiration=" + iso + "." + fraction + "Z";
}

// The oracle's shape classification: quoted on both ends and nothing after.
bool query_shape(const std::string& raw) {
    return raw.size() >= 2 && raw.front() == '"' && raw.back() == '"';
}

// Mirrors Probe.DescribeTheme. Two normalizations, both because the oracle's
// inputs are machine-dependent rather than because the port is allowed to drift:
//   * the theme directory is a Path.GetRandomFileName() name;
//   * the copy constructor re-initializes AppVersion from the ENTRY ASSEMBLY, so
//     the probe's value is 1.0.0.0 and the port's is kThemeDefaultAppVersion.
std::string describe_theme(const models::ThemeModel& theme, std::string dir = {},
                           bool mask_app_version = false) {
    const auto or_null = [](const std::optional<std::string>& v) {
        return v ? *v : std::string("<null>");
    };

    std::string tags = "<null>";
    if (theme.tags) {
        tags.clear();
        for (std::size_t i = 0; i < theme.tags->size(); ++i) {
            if (i) tags += "|";
            tags += (*theme.tags)[i];
        }
    }

    std::string text = "appVersion=" + (mask_app_version ? std::string("<HOST>") : theme.app_version) +
                       ";name=" + or_null(theme.name) + ";description=" + or_null(theme.description) +
                       ";contact=" + or_null(theme.contact) + ";license=" + or_null(theme.license) +
                       ";file=" + or_null(theme.file) + ";preview=" + or_null(theme.preview) +
                       ";accentColor=" + or_null(theme.accent_color) +
                       ";type=" + std::to_string(static_cast<int>(theme.type)) + ";tags=" + tags +
                       ";isEditable=" + (theme.is_editable ? "True" : "False");

    if (!dir.empty()) {
        std::size_t pos = 0;
        while ((pos = text.find(dir, pos)) != std::string::npos) {
            text.replace(pos, dir.size(), "<THEME_DIR>");
            pos += 11;  // strlen("<THEME_DIR>")
        }
    }
    for (char& c : text) {
        if (c == '\\') c = '/';
    }
    return text;
}

const std::vector<unsigned char> kBytes = {1, 2, 3, 255, 0, 16, 128};

std::vector<models::ApplicationRulesModel> sample_rules() {
    return {
        {"vlc.exe", models::AppRules::pause},
        {"game.exe", models::AppRules::kill},
        {"whatever", models::AppRules::ignore},
    };
}

std::vector<models::AppMusicExclusionRuleModel> sample_music_rules() {
    // Second entry exercises a null AppPath and non-ASCII text.
    return {
        {"Spotify", std::string("C:\\Users\\x\\AppData\\Roaming\\Spotify\\Spotify.exe")},
        {"Ünïcode ✓", std::nullopt},
    };
}

models::gallery::TokensModel sample_tokens() {
    models::gallery::TokensModel tokens;
    tokens.access_token = "access-token-!@#$%^&*()";
    tokens.refresh_token = "refresh-token";
    tokens.provider = "google";
    tokens.expiration_iso = "2030-06-01T12:30:45Z";
    return tokens;
}

} // namespace

TEST_CASE("JsonStorage<byte[]> writes a base64 JSON string", "[persist][oracle]") {
    const std::string path = write_temp_file("Bytes.json");
    common::JsonStorage::StoreBytesData(path, kBytes);

    const std::string text = read_file(path);
    CHECK(escaped(text) == golden_value("jsonstorage.bytes"));
    // A byte[] is a scalar, so Formatting.Indented is a no-op: no trailing
    // newline, and the file is exactly the quoted base64 with no indentation.
    CHECK(text.front() == '"');
    CHECK(text.back() == '"');

    const auto reloaded = common::JsonStorage::LoadBytesData(path);
    CHECK(hex(reloaded) == golden_value("jsonstorage.bytes.reload"));

    // C# writes an empty array as "" — an empty JSON string, not null.
    const std::string empty_path = write_temp_file("Empty.json");
    common::JsonStorage::StoreBytesData(empty_path, {});
    CHECK(escaped(read_file(empty_path)) == golden_value("jsonstorage.bytes.empty"));
}

TEST_CASE("base64 matches Convert.ToBase64String", "[persist][base64]") {
    CHECK(common::base64_encode(kBytes) == "AQID/wAQgA==");
    CHECK(common::base64_encode({}) == "");

    const auto decoded = common::base64_decode("AQID/wAQgA==");
    REQUIRE(decoded.has_value());
    CHECK(hex(*decoded) == "010203ff001080");

    // .NET throws rather than guessing: wrong length, bad alphabet, misplaced
    // padding and whitespace are all rejected.
    CHECK_FALSE(common::base64_decode("AQID/wAQgA=").has_value());
    CHECK_FALSE(common::base64_decode("AQID*wAQgA==").has_value());
    CHECK_FALSE(common::base64_decode("AQID/wAQgA==\n").has_value());
    CHECK_FALSE(common::base64_decode("=QID/wAQgA==").has_value());
    CHECK_FALSE(common::base64_decode("AA==AAAA").has_value());
}

TEST_CASE("AppRules.json matches the C# bytes", "[persist][oracle]") {
    const std::string path = write_temp_file("AppRules.json");
    common::JsonStorage::StoreAppRulesData(path, sample_rules());

    CHECK(escaped(read_file(path)) == golden_value("apprules.serialize"));

    const auto reloaded = common::JsonStorage::LoadAppRulesData(path);
    std::string joined;
    for (const auto& rule : reloaded) {
        if (!joined.empty()) joined += ";";
        joined += rule.app_name + "=" + std::to_string(static_cast<int>(rule.rule));
    }
    CHECK(joined == golden_value("apprules.reload"));
    // Enum ordinals are the persisted contract: pause=0, ignore=1, kill=2.
    REQUIRE(reloaded.size() == 3);
    CHECK(static_cast<int>(reloaded[0].rule) == 0);
    CHECK(static_cast<int>(reloaded[1].rule) == 2);
    CHECK(static_cast<int>(reloaded[2].rule) == 1);
}

TEST_CASE("MusicAppExclusionRules.json matches the C# bytes", "[persist][oracle]") {
    const std::string path = write_temp_file("MusicAppExclusionRules.json");
    common::JsonStorage::StoreMusicExclusionRulesData(path, sample_music_rules());

    CHECK(escaped(read_file(path)) == golden_value("musicexclusion.serialize"));

    const auto reloaded = common::JsonStorage::LoadMusicExclusionRulesData(path);
    REQUIRE(reloaded.size() == 2);
    CHECK(reloaded[0].app_name == "Spotify");
    REQUIRE(reloaded[0].app_path.has_value());
    CHECK(*reloaded[0].app_path == "C:\\Users\\x\\AppData\\Roaming\\Spotify\\Spotify.exe");
    CHECK(reloaded[1].app_name == "Ünïcode ✓");
    // A null AppPath stays null on the way back in (not an empty string).
    CHECK_FALSE(reloaded[1].app_path.has_value());
}

TEST_CASE("Tokens.dat plaintext is Newtonsoft's serialization", "[persist][oracle]") {
    // EncryptUtil.Protect<T> encrypts UTF8(JsonConvert.SerializeObject(data)),
    // and that plaintext is deterministic even though the blob is not.
    CHECK(escaped(sample_tokens().to_json().dump()) == golden_value("tokenstore.plaintext"));
    CHECK(escaped(models::gallery::TokensModel{}.to_json().dump()) ==
          golden_value("tokenstore.plaintext.empty"));
}

TEST_CASE("Expiration normalizes to Newtonsoft's DateTime rendering",
          "[persist][expiration]") {
    using models::gallery::normalize_expiration;

    // A real token response.
    CHECK(normalize_expiration("2030-06-01T12:30:45Z") == "2030-06-01T12:30:45Z");
    // Zero fractions are dropped entirely; non-zero fractions keep their digits.
    CHECK(normalize_expiration("2030-06-01T12:30:45.0000000Z") == "2030-06-01T12:30:45Z");
    CHECK(normalize_expiration("2030-06-01T12:30:45.7890000Z") == "2030-06-01T12:30:45.789Z");
    CHECK(normalize_expiration("2030-06-01T12:30:45.12345678Z") == "2030-06-01T12:30:45.1234567Z");
    // No suffix means DateTimeKind.Unspecified and the kind is never invented.
    CHECK(normalize_expiration("2030-06-01T12:30:45") == "2030-06-01T12:30:45");
    // default(DateTime) — note: no Z, which is a DIFFERENT string from
    // "...:00Z" and is exactly what C# writes for an unset Expiration.
    CHECK(normalize_expiration("") == "0001-01-01T00:00:00");
    CHECK(normalize_expiration("garbage") == "0001-01-01T00:00:00");
    // A bare date and a missing-seconds time are both legal ISO.
    CHECK(normalize_expiration("2030-06-01") == "2030-06-01T00:00:00");
    CHECK(normalize_expiration("2030-06-01T12:30") == "2030-06-01T12:30:00");
    // Documented deviation: a numeric offset stays verbatim (converting it to
    // local time, as C# does, would make the result machine-dependent).
    CHECK(normalize_expiration("2030-06-01T12:30:45+02:00") == "2030-06-01T12:30:45+02:00");

    // And it is wired into deserialization, not just available to callers.
    const auto parsed = models::gallery::TokensModel::from_json(
        nlohmann::ordered_json::parse("{\"Expiration\":\"2030-06-01T12:30:45.0000000Z\"}"));
    CHECK(parsed.expiration_iso == "2030-06-01T12:30:45Z");
}

TEST_CASE("Tokens.dat round-trips through DPAPI", "[persist][oracle][dpapi]") {
    const std::string path = write_temp_file("Tokens.dat");

    common::store_tokens(path, sample_tokens());

    // The wrapper shape: a quoted JSON string, on a single line. This is the
    // assertion that catches a port writing plaintext JSON to disk.
    const std::string raw = read_file(path);
    REQUIRE_FALSE(raw.empty());
    CHECK(raw.front() == '"');
    CHECK(raw.back() == '"');
    CHECK(raw.find('\n') == std::string::npos);
    // The oracle's own classification of the file it wrote — a port that emitted
    // plaintext JSON would be "other"/"multiline" here.
    CHECK(golden_value("tokenstore.shape") == (query_shape(raw) ? "quoted-string" : "other"));
    CHECK(golden_value("tokenstore.single-line") ==
          (raw.find('\n') == std::string::npos ? "single-line" : "multiline"));

    // The plaintext must not be recoverable from the file.
    CHECK(raw.find("access-token") == std::string::npos);

    const auto reloaded = common::load_tokens(path);
    CHECK(describe_tokens(reloaded) == golden_value("tokenstore.reload"));

    // An empty store (the Clear() path) writes a valid file too.
    const std::string empty_path = write_temp_file("TokensEmpty.dat");
    common::store_tokens(empty_path, models::gallery::TokensModel{});
    CHECK(describe_tokens(common::load_tokens(empty_path)) == golden_value("tokenstore.empty"));

    // Entropy is bound to the app alias: a blob written with different entropy
    // must fail to decrypt rather than silently return garbage. This is the
    // "user copied Tokens.dat from another machine" case.
    const std::string foreign = write_temp_file("Foreign.dat");
    {
        const auto blob = common::protect_data(std::vector<unsigned char>{'x', 'y'});
        common::JsonStorage::StoreBytesData(foreign, blob);
    }
    // Re-protecting with a corrupt payload must throw, not crash.
    std::vector<unsigned char> tampered = common::JsonStorage::LoadBytesData(foreign);
    REQUIRE(tampered.size() > 8);
    tampered[8] ^= 0xFF;  // flip a bit inside the DPAPI blob
    common::JsonStorage::StoreBytesData(foreign, tampered);
    CHECK_THROWS(common::load_tokens(foreign));
}

TEST_CASE("JsonTokenStore persists a login across instances", "[persist][tokenstore]") {
    const std::string path = write_temp_file("StoreTokens.dat");

    {
        gallery::JsonTokenStore store(path);
        // Not logged in yet: a missing file must read as "no tokens", not throw.
        CHECK_FALSE(store.get().access_token.has_value());
        CHECK(store.get().expiration_iso == "0001-01-01T00:00:00");

        store.set("access", "refresh", "GOOGLE", "2030-06-01T12:30:45Z");
        const auto cached = store.get();
        REQUIRE(cached.access_token.has_value());
        CHECK(*cached.access_token == "access");
        CHECK(*cached.provider == "GOOGLE");
    }

    // A fresh instance (i.e. the next app launch) reads it back off the disk.
    gallery::JsonTokenStore reopened(path);
    const auto tokens = reopened.get();
    REQUIRE(tokens.access_token.has_value());
    CHECK(*tokens.access_token == "access");
    CHECK(*tokens.refresh_token == "refresh");
    CHECK(*tokens.provider == "GOOGLE");
    CHECK(tokens.expiration_iso == "2030-06-01T12:30:45Z");

    // clear() replaces the file with an empty store.
    reopened.clear();
    gallery::JsonTokenStore cleared(path);
    CHECK_FALSE(cleared.get().access_token.has_value());

    // A corrupt file must degrade to "not logged in", never throw: this is the
    // C# `catch { }` in Get(), and it is what keeps a corrupted Tokens.dat from
    // stopping the app from starting.
    const std::string corrupt = write_temp_file("Corrupt.dat");
    {
        std::ofstream out(corrupt, std::ios::binary | std::ios::trunc);
        out << "not json at all";
    }
    gallery::JsonTokenStore broken(corrupt);
    CHECK_FALSE(broken.get().access_token.has_value());
}

TEST_CASE("JsonTokenStore defaults to CommonPaths.TokensPath", "[persist][constants]") {
    gallery::JsonTokenStore store;
    CHECK(store.path().find("Tokens.dat") != std::string::npos);
    CHECK(store.path().find("Lively Wallpaper") != std::string::npos);
}

TEST_CASE("theme.json matches the C# bytes", "[persist][theme][oracle]") {
    models::ThemeModel theme;
    theme.app_version = "0.0.0.0";
    theme.name = "My Theme";
    theme.description = "desc";
    theme.accent_color = "#FFAA00";
    theme.file = "picture.png";
    theme.preview = "preview.png";
    theme.type = models::ThemeType::picture;
    theme.tags = std::vector<std::string>{"dark", "minimal"};
    theme.is_editable = true;  // must NOT be written ([JsonIgnore])

    CHECK(escaped(theme.to_json_string()) == golden_value("theme.serialize"));
    // The [JsonIgnore] guarantee, asserted directly rather than only through the
    // byte comparison, because it is the one member a port adds by accident.
    CHECK(theme.to_json_string().find("IsEditable") == std::string::npos);
    CHECK(theme.to_json_string().find("isEditable") == std::string::npos);

    const models::ThemeModel back = models::ThemeModel::from_json(
        nlohmann::ordered_json::parse(theme.to_json_string()));
    CHECK(describe_theme(back) == golden_value("theme.reload"));
    CHECK(back.app_version == golden_value("theme.reload.appversion"));
    // Runtime-only state is false after a round trip, never true.
    CHECK_FALSE(back.is_editable);
    REQUIRE(back.tags.has_value());
    CHECK(back.tags->size() == 2);

    // Every other nullable member is a plain C# `string` with no initializer, so
    // a default-constructed model writes nulls — not empty strings. `Name` is in
    // that set; only AppVersion has an initializer.
    models::ThemeModel bare;
    bare.app_version = "0.0.0.0";
    CHECK(escaped(bare.to_json_string()) == golden_value("theme.serialize.bare"));
}

TEST_CASE("the C# ThemeModel copy constructor does not copy AppVersion",
          "[persist][theme][regression]") {
    models::ThemeModel source;
    source.app_version = "9.9.9.9";  // a non-default app version
    source.name = "Theme";
    source.file = "a.png";
    source.preview = "p.png";
    source.tags = std::vector<std::string>{"t"};
    source.is_editable = true;

    const models::ThemeModel copy = models::ThemeModel::copy_constructor(source);

    // The quirk: AppVersion is re-initialized, not carried over. This is
    // observable — it is what an installed theme's theme.json ends up recording.
    CHECK(copy.app_version == models::kThemeDefaultAppVersion);
    CHECK(copy.app_version != source.app_version);
    // Everything else IS copied.
    CHECK(copy.name == source.name);
    CHECK(copy.file == source.file);
    CHECK(copy.preview == source.preview);
    REQUIRE(copy.tags.has_value());
    CHECK(*copy.tags == *source.tags);
    // IsEditable is not assigned by the C# copy constructor either.
    CHECK_FALSE(copy.is_editable);
}

TEST_CASE("AppThemeFactory matches the C# create/read behaviour",
          "[persist][theme][oracle]") {
    const std::string themes_dir = write_temp_file("themes") ;
    const std::string source = write_temp_file("source.png");
    {
        std::ofstream out(source, std::ios::binary | std::ios::trunc);
        out << "\x89PNG";
    }

    common::factories::AppThemeFactory factory(themes_dir);
    const models::ThemeModel created = factory.CreateFromFile(source, "Wallpaper Theme", "a description");

    CHECK(created.is_editable);
    REQUIRE(created.file.has_value());
    // The returned model holds the ABSOLUTE copied path...
    CHECK(created.file->find("source.png") != std::string::npos);
    // ...and the theme directory is a Path.GetRandomFileName() child of ThemeDir,
    // which is exactly what the oracle masks (it masked created.Dir, not ThemeDir).
    REQUIRE(common::path::get_directory_name(*created.file).has_value());
    const std::string theme_dir = *common::path::get_directory_name(*created.file);
    CHECK(common::path::get_directory_name(theme_dir) == std::optional(themes_dir));

    CHECK(describe_theme(created, theme_dir) == golden_value("theme.factory.created"));

    // The persisted file records only filenames, relative to the theme
    // directory, and (via the copy constructor) the host's AppVersion.
    const std::string stored_json = read_file(common::path::combine(theme_dir, "theme.json"));
    REQUIRE_FALSE(stored_json.empty());
    CHECK(stored_json.find("IsEditable") == std::string::npos);
    CHECK(stored_json.find("\"File\": \"source.png\"") != std::string::npos);
    CHECK(stored_json.find("\"Preview\": \"source.png\"") != std::string::npos);
    // The copied model's AppVersion is the host's, not the source model's — the
    // source was created with the port's default, so this only proves it is the
    // default here; the discriminating test is the copy-constructor case below.
    CHECK(created.app_version == models::kThemeDefaultAppVersion);

    // Reading it back re-roots File/Preview at the theme directory.
    const models::ThemeModel loaded = factory.CreateFromDirectory(theme_dir);
    CHECK(loaded.is_editable);
    REQUIRE(loaded.file.has_value());
    REQUIRE(loaded.preview.has_value());
    CHECK(*loaded.file == *created.file);
    CHECK(*loaded.preview == *created.preview);
    // masked: the read-back path also goes through the copy constructor, so the
    // AppVersion here is the host's, and the golden records it as <HOST>.
    CHECK(describe_theme(loaded, theme_dir, true) == golden_value("theme.factory.loaded"));
    CHECK(loaded.app_version == models::kThemeDefaultAppVersion);

    // A directory with no theme.json raises rather than returning a blank model
    // (C# FileNotFoundException).
    const std::string empty_dir = write_temp_file("no_theme");
    CHECK_THROWS(factory.CreateFromDirectory(empty_dir));

    // A theme.json whose File member is absent must fail: C# calls
    // Path.Combine(dir, null), which throws, rather than resolving to the
    // directory itself.
    const std::string partial_dir = write_temp_file("partial_theme");
    std::error_code ec;
    fs::create_directories(fs::u8path(partial_dir), ec);
    {
        std::ofstream out(partial_dir + "\\theme.json", std::ios::binary | std::ios::trunc);
        out << "{\"AppVersion\":\"0.0.0.0\",\"Name\":\"x\"}";
    }
    CHECK_THROWS(factory.CreateFromDirectory(partial_dir));

    // Also verify the golden's own normalizations are what we think they are — a
    // fixture that silently drifted would make the comparisons above vacuous.
    CHECK(golden_value("theme.factory.editable") == "True");
}
