// True characterization test: reads the Newtonsoft.Json output captured from
// the real C# binaries (tests/goldens/ipc_csharp.txt, generated by
// tools/csharp_probe) and requires the C++ port to serialize byte-identically.
// If the C# models change, regenerate the fixture and this test fails until
// the C++ port is updated — keeping the C# app as the reference oracle.
#include <catch2/catch_test_macros.hpp>

#include <lively/models/ipc_message.h>

#include <cstdio>
#include <fstream>
#include <iostream>
#include <map>
#include <string>
#include <vector>

#include <nlohmann/json.hpp>

using namespace lively::models;

namespace {

std::string goldens_path() {
#ifndef LIVELY_GOLDENS_DIR
#define LIVELY_GOLDENS_DIR "tests/goldens"
#endif
    return std::string(LIVELY_GOLDENS_DIR) + "/ipc_csharp.txt";
}

// name -> exact C# output line (trailing \r\n stripped).
std::map<std::string, std::string> load_goldens() {
    std::map<std::string, std::string> out;
    std::ifstream in(goldens_path(), std::ios::binary);
    REQUIRE(in.good());
    std::string line;
    while (std::getline(in, line)) {
        if (!line.empty() && line.back() == '\r') line.pop_back();
        if (line.empty()) continue;
        const auto tab = line.find('\t');
        REQUIRE(tab != std::string::npos);
        out[line.substr(0, tab)] = line.substr(tab + 1);
    }
    return out;
}

std::string wire(const IpcMessage& msg) { return lively::models::serialize(msg); }

} // namespace

TEST_CASE("C++ IPC wire output equals captured C# Newtonsoft output", "[ipc][golden][oracle]") {
    const auto goldens = load_goldens();

    // Producers must mirror every expectation the probe emitted.
    LivelyVolumeCmd volume;
    volume.volume = 42;
    LivelyMessageHwnd hwnd;
    hwnd.hwnd = 65535;
    LivelyMessageWallpaperLoaded wploaded;
    wploaded.success = true;
    LivelyMessageConsole console;
    console.message = "hello";
    console.category = ConsoleMessageType::error;
    LivelyMessageConsole console_null; // message empty => C# null probe used default instance
    LivelySlider slider;
    slider.name = "Speed";
    slider.value = 1.5;
    slider.step = 0.5;
    LivelyTextBox textbox;
    textbox.name = "Note";
    textbox.value = "abc";
    LivelyCheckbox checkbox;
    checkbox.name = "Enabled";
    checkbox.value = true;
    LivelyDropdown dropdown;
    dropdown.name = "Quality";
    dropdown.value = 2;
    LivelyButton button;
    button.name = "Apply";
    button.is_default = true;
    LivelyColorPicker color_picker;
    color_picker.name = "Tint";
    color_picker.value = "#FFAA00";
    // Read by the mpv host as a WallpaperScaler ordinal (lp_dropdown_scaler).
    LivelyDropdownScaler scaler_dropdown;
    scaler_dropdown.name = "Scaler";
    scaler_dropdown.value = 3;
    LivelyMessageConsole unicode;
    unicode.message = "\u58c1\u7d19 \"test\"\nline2"; // 壁紙

    const std::vector<std::pair<std::string, std::string>> actual = {
        {"LivelyCloseCmd.default", wire(LivelyCloseCmd{})},
        {"LivelySuspendCmd.default", wire(LivelySuspendCmd{})},
        {"LivelyResumeCmd.default", wire(LivelyResumeCmd{})},
        {"LivelyReloadCmd.default", wire(LivelyReloadCmd{})},
        {"LivelyVolumeCmd.default", wire(LivelyVolumeCmd{})},
        {"LivelyVolumeCmd.v42", wire(volume)},
        {"LivelyMessageHwnd.65535", wire(hwnd)},
        {"LivelyMessageWallpaperLoaded.success", wire(wploaded)},
        {"LivelyMessageConsole.error", wire(console)},
        {"LivelySlider.populated", wire(slider)},
        {"LivelyTextBox.populated", wire(textbox)},
        {"LivelyCheckbox.checked", wire(checkbox)},
        {"LivelyDropdown.populated", wire(dropdown)},
        {"LivelyButton.default", wire(button)},
        {"LivelyColorPicker.populated", wire(color_picker)},
        {"LivelyDropdownScaler.populated", wire(scaler_dropdown)},
        {"LivelyMessageConsole.unicode", wire(unicode)},
    };

    for (const auto& [name, actual_json] : actual) {
        const auto it = goldens.find(name);
        REQUIRE(it != goldens.end());
        INFO("fixture: " << name << "\n  csharp: " << it->second << "\n  c++:    " << actual_json);
        REQUIRE(actual_json == it->second);
    }
}

TEST_CASE("C# null string serializes as JSON null (oracle case)", "[ipc][golden][oracle]") {
    const auto goldens = load_goldens();
    // The probe's nullMessage fixture has Message=null; our optional<string>
    // models C# null via a dedicated construction path in C++ once messaging
    // supports it — here we assert the JSON shape matches Newtonsoft's.
    const auto it = goldens.find("LivelyMessageConsole.nullMessage");
    REQUIRE(it != goldens.end());
    const auto j = nlohmann::ordered_json::parse(it->second);
    REQUIRE(j["Message"].is_null());
    REQUIRE(j["Category"].get<int>() == 0);
}

TEST_CASE("unicode escaping matches Newtonsoft", "[ipc][golden][oracle]") {
    // Newtonsoft does not escape non-ASCII (emits raw UTF-8) but escapes
    // quote and newline — verified against the captured fixture.
    const auto goldens = load_goldens();
    const auto it = goldens.find("LivelyMessageConsole.unicode");
    REQUIRE(it != goldens.end());
    REQUIRE(it->second.find("\u58c1\u7d19") != std::string::npos);      // raw CJK
    REQUIRE(it->second.find("\\\"test\\\"") != std::string::npos);      // escaped quotes
    REQUIRE(it->second.find("\\nline2") != std::string::npos);          // escaped newline
}
