// SettingsModel equivalence tests.
//
// 1. Oracle: byte-compare SettingsModel::to_json_string() (with the two
//    machine-dependent fields canonicalized) against the JSON captured from
//    the real C# SettingsModel + Newtonsoft (tests/goldens/settings_csharp.json,
//    generated by `csharp_probe settings`).
// 2. Roundtrip: parse(serialize(m)) == m for the default model.
#include <catch2/catch_test_macros.hpp>

#include <lively/models/settings_model.h>

#include <fstream>
#include <sstream>
#include <string>

using namespace lively;

#ifdef LIVELY_GOLDENS_DIR
static std::string read_file(const std::string& path) {
    std::ifstream in(path);
    std::stringstream ss;
    ss << in.rdbuf();
    return ss.str();
}

TEST_CASE("SettingsModel serializes byte-identically to the C# oracle", "[settings]") {
    models::SettingsModel m;
    // Canonicalize the machine-dependent fields (probe does the same).
    m.app_version = "0.0.0.0";
    m.wallpaper_dir = "C:\\Users\\canon\\AppData\\Local\\Lively Wallpaper\\Library";

    std::string expected = read_file(LIVELY_GOLDENS_DIR "/settings_csharp.json");
    REQUIRE(!expected.empty());
    // strip trailing newline the shell redirect adds on Windows
    while (!expected.empty() && (expected.back() == '\n' || expected.back() == '\r')) {
        expected.pop_back();
    }
    std::string actual = m.to_json_string();
    INFO("expected: " << expected.substr(0, 200));
    INFO("actual:   " << actual.substr(0, 200));
    CHECK(actual == expected);
}
#endif

TEST_CASE("SettingsModel roundtrips through JSON without loss", "[settings]") {
    models::SettingsModel m;
    m.app_version = "9.9.9.9";
    m.selected_display = std::make_shared<models::DisplayMonitor>();
    m.selected_display->device_id = "\\\\?\\DISPLAY#7";
    m.selected_display->is_primary = true;
    m.selected_display->bounds = {0, 0, 1920, 1080};
    m.selected_display->working_area = {0, 48, 1920, 1032};
    m.selected_audio_output_display = std::make_shared<models::DisplayMonitor>();
    m.selected_audio_output_display->device_id = "\\\\?\\DISPLAY#2";
    m.screensaver_idle_delay = models::ScreensaverIdleTime::min15;
    m.video_player = models::LivelyMediaPlayer::vlc;
    m.audio_volume_global = 33;

    const std::string json = m.to_json_string();
    const auto back = models::SettingsModel::from_json_string(json);

    CHECK(back.app_version == "9.9.9.9");
    CHECK(back.selected_display->device_id == "\\\\?\\DISPLAY#7");
    CHECK(back.selected_display->bounds.height == 1080);
    CHECK(back.selected_audio_output_display->device_id == "\\\\?\\DISPLAY#2");
    CHECK(back.screensaver_idle_delay == models::ScreensaverIdleTime::min15);
    CHECK(back.video_player == models::LivelyMediaPlayer::vlc);
    CHECK(back.audio_volume_global == 33);
    // Defaults survive for untouched fields.
    CHECK(back.saved_url == "https://www.youtube.com/watch?v=aqz-KE-bpKQ");
    CHECK(back.process_monitor_algorithm == models::ProcessMonitorAlgorithm::grid);
    CHECK(back.wallpaper_dir_move_existing_wallpaper_new_dir);
}

TEST_CASE("SettingsModel defaults match the C# constructor", "[settings]") {
    models::SettingsModel m;
    CHECK(m.saved_url == "https://www.youtube.com/watch?v=aqz-KE-bpKQ");
    CHECK(m.process_monitor_algorithm == models::ProcessMonitorAlgorithm::grid);
    CHECK(m.video_player == models::LivelyMediaPlayer::mpv);
    CHECK(m.web_browser == models::LivelyWebBrowser::webview2);
    CHECK(m.gif_player == models::LivelyGifPlayer::mpv);
    CHECK(m.audio_volume_global == 75);
    CHECK(m.wallpaper_wait_time == 20000);
    CHECK(m.process_timer_interval == 500);
    CHECK(m.wallpaper_bundle_version == -1);
    CHECK(m.theme_bundle_version == -1);
    CHECK(m.taskbar_crash_time_out_delay == 30);
    CHECK(m.screensaver_grace_period == 5);
    CHECK(m.application_theme == models::AppTheme::Dark);
    CHECK(m.application_theme_background == models::AppThemeBackground::default_mica);
    CHECK(m.is_screensaver_plugin_notify);
    CHECK(m.screensaver_empty_screen_show_black);
    CHECK(m.screensaver_fade_in);
    CHECK(m.stream_quality == models::StreamQualitySuggestion::High);
    CHECK(m.input_forward == models::InputForwardMode::mouse);
    CHECK(m.tile_size == 1);
    CHECK(m.process_monitor_grid_tile_coverage_threshold == 0.05);
    CHECK(m.process_monitor_grid_tile_size == 50);
    CHECK(m.is_first_run);
    CHECK(m.startup);
    CHECK(m.app_focus_pause == models::AppRules::ignore);
    CHECK(m.app_fullscreen_pause == models::AppRules::pause);
    CHECK(m.battery_pause == models::AppRules::ignore);
    CHECK(m.remote_desktop_pause == models::AppRules::pause);
    CHECK(m.power_save_mode_pause == models::AppRules::ignore);
    CHECK(m.scaler_video == models::WallpaperScaler::fill);
    CHECK(m.scaler_gif == models::WallpaperScaler::fill);
    CHECK(m.wallpaper_scaling == models::WallpaperScaler::fill);
    CHECK(m.display_identification == models::DisplayIdentificationMode::deviceId);
    CHECK(m.screensaver_idle_delay == models::ScreensaverIdleTime::none);
    CHECK(m.selected_display == nullptr);
    CHECK(m.selected_audio_output_display == nullptr);
    CHECK(m.wallpaper_dir.find("Lively Wallpaper\\Library") != std::string::npos);
}
