// The desktop placement rules — which wallpaper belongs on which screen when
// displays come and go — replayed against the C# oracle
// (tests/goldens/desktop_layout_csharp.txt, generated by
// `csharp_probe desktoplayout`).
//
// The C# logic is not directly callable: it lives inside WinDesktopCore behind
// WorkerW parenting and SetWindowPos. So `DesktopLayoutProbe` re-expresses the
// same rules using the LINQ expressions copied verbatim from the source, and the
// port re-expresses them with ordinary loops. The two implementations differ
// mechanically, which is what makes the comparison worth anything.
//
// The scenarios here are the ones where a port silently diverges: monitor
// unplugged under each arrangement, an already-queued display (dedupe by
// DeviceId only), the span rect rebased on a negative-origin virtual screen, and
// the reference-vs-value identity question in RestoreWallpaper.

#include <catch2/catch_test_macros.hpp>

#include <lively/core/desktop_layout.h>
#include <lively/models/display_monitor.h>
#include <lively/models/settings_model.h>
#include <lively/models/wallpaper_layout.h>

#include <algorithm>
#include <fstream>
#include <memory>
#include <sstream>
#include <string>
#include <vector>

using namespace lively;
using core::RefreshPlan;
using core::RectPlan;
using core::RestorePlan;
using core::RestoreSource;
using core::WallpaperSlot;
using models::DisplayMonitor;
using models::WallpaperArrangement;
using models::WallpaperLayoutModel;

namespace {

#ifdef LIVELY_GOLDENS_DIR
const std::string kGoldensDir = LIVELY_GOLDENS_DIR;
#else
const std::string kGoldensDir = "tests/goldens";
#endif

std::string read_file(const std::string& path) {
    std::ifstream in(path, std::ios::binary);
    if (!in) return {};
    std::stringstream ss;
    ss << in.rdbuf();
    return ss.str();
}

std::string golden_value(const std::string& key) {
    const std::string text = read_file(kGoldensDir + "/desktop_layout_csharp.txt");
    REQUIRE_FALSE(text.empty());
    std::size_t pos = 0;
    while (pos < text.size()) {
        std::size_t end = text.find('\n', pos);
        if (end == std::string::npos) end = text.size();
        std::string line = text.substr(pos, end - pos);
        if (!line.empty() && line.back() == '\r') line.pop_back();
        const std::size_t tab = line.find('\t');
        if (tab != std::string::npos && line.substr(0, tab) == key) return line.substr(tab + 1);
        pos = end + 1;
    }
    return {};
}

// ---- the same synthetic displays the probe builds ---------------------------

DisplayMonitor disp(const std::string& id, int x, int y, int w, int h, bool primary = false) {
    DisplayMonitor d;
    d.device_id = id;
    d.device_name = id;
    d.display_name = id;
    d.is_primary = primary;
    d.bounds = models::Rectangle{x, y, w, h};
    d.working_area = models::Rectangle{x, y, w, h};
    return d;
}

DisplayMonitor primary_display() { return disp("P", 0, 0, 1920, 1080, true); }
DisplayMonitor secondary_display() { return disp("S", 1920, 0, 1920, 1080); }
DisplayMonitor third_display() { return disp("T", 3840, 0, 1280, 1024); }

// C# DisplayManager.PrimaryDisplayMonitor — first with IsPrimary.
DisplayMonitor primary_of(const std::vector<DisplayMonitor>& displays) {
    for (const auto& d : displays) {
        if (d.is_primary) return d;
    }
    return displays.empty() ? DisplayMonitor{} : displays[0];
}

// A fresh 3-screen list: plan_refresh does not mutate (unlike the C# RemoveAll),
// so the test applies the removal when a scenario needs the second pass.
std::vector<WallpaperSlot> new_wallpapers() {
    return {
        {primary_display(), "wp-a"},
        {secondary_display(), "wp-b"},
        {third_display(), "wp-c"},
    };
}

// The caller side of "orphans are disposed and removed from the live list".
//
// Only `per` and `duplicate` do this — the C# `span` case is a bare `break`,
// because one wallpaper spans every screen and has no per-screen entry to
// remove. Applying the removal unconditionally is exactly the kind of drift this
// fixture is meant to catch (it did: `refresh.twice.span`).
void apply_orphan_removal(std::vector<WallpaperSlot>& wallpapers, const RefreshPlan& plan,
                          WallpaperArrangement arrangement) {
    if (arrangement == WallpaperArrangement::span) return;
    for (const auto& orphan : plan.orphans) {
        wallpapers.erase(std::remove_if(wallpapers.begin(), wallpapers.end(),
                                        [&](const WallpaperSlot& wallpaper) {
                                            return wallpaper.on(orphan.screen) &&
                                                   wallpaper.lively_info_path == orphan.lively_info_path;
                                        }),
                         wallpapers.end());
    }
}

std::string refresh_report(const std::vector<WallpaperSlot>& wallpapers,
                           const std::vector<DisplayMonitor>& displays,
                           const std::vector<WallpaperLayoutModel>& disconnected,
                           WallpaperArrangement arrangement, const DisplayMonitor& selected) {
    return core::describe_refresh(core::plan_refresh(wallpapers, displays, disconnected, arrangement,
                                                     selected, primary_of(displays)));
}

std::vector<WallpaperLayoutModel> layout_entries(const std::vector<WallpaperSlot>& wallpapers) {
    std::vector<WallpaperLayoutModel> out;
    for (const auto& wallpaper : wallpapers) {
        out.emplace_back(std::make_shared<DisplayMonitor>(wallpaper.screen), wallpaper.lively_info_path);
    }
    return out;
}

const std::vector<WallpaperArrangement> kArrangements = {
    WallpaperArrangement::per, WallpaperArrangement::span, WallpaperArrangement::duplicate};

std::string arrangement_name(WallpaperArrangement arrangement) {
    switch (arrangement) {
        case WallpaperArrangement::per: return "per";
        case WallpaperArrangement::span: return "span";
        case WallpaperArrangement::duplicate: return "duplicate";
    }
    return "?";
}

} // namespace

TEST_CASE("display placement rules match the C# oracle", "[desktop][oracle]") {
    const DisplayMonitor primary = primary_display();
    const DisplayMonitor secondary = secondary_display();
    const DisplayMonitor third = third_display();

    std::vector<std::pair<std::string, std::string>> lines;
    const auto record = [&lines](const std::string& key, const std::string& value) {
        lines.emplace_back(key, value);
    };

    // ---- RefreshWallpaper(): one screen removed, per arrangement ------------
    const std::vector<DisplayMonitor> visible = {primary, secondary};  // third unplugged
    for (const auto arrangement : kArrangements) {
        const std::string tag = arrangement_name(arrangement);

        record("refresh.removed." + tag,
               refresh_report(new_wallpapers(), visible, {}, arrangement, secondary));
        record("refresh.removed.dedup." + tag,
               refresh_report(new_wallpapers(), visible,
                              {WallpaperLayoutModel(std::make_shared<DisplayMonitor>(third), "wp-c")},
                              arrangement, secondary));
        // Dedupe is DeviceId-only, so a stale-bounds entry for the same screen
        // suppresses the new one too.
        record("refresh.removed.dedup-stale-bounds." + tag,
               refresh_report(new_wallpapers(), visible,
                              {WallpaperLayoutModel(
                                  std::make_shared<DisplayMonitor>(disp("T", 0, 0, 1, 1)), "wp-old")},
                              arrangement, secondary));
        record("refresh.stable." + tag,
               refresh_report(new_wallpapers(), {primary, secondary, third}, {}, arrangement, secondary));

        // Two passes over one live list: the orphan is already gone the second time.
        auto live = new_wallpapers();
        apply_orphan_removal(live,
                             core::plan_refresh(live, visible, {}, arrangement, secondary,
                                                primary_of(visible)),
                             arrangement);
        record("refresh.twice." + tag,
               refresh_report(live, visible, {}, arrangement, secondary));
    }

    // One wallpaper, so these scenarios isolate the selected-display fallback.
    const std::vector<WallpaperSlot> one_wallpaper = {{primary, "wp-a"}};
    record("refresh.selected.fallback",
           refresh_report(one_wallpaper, {primary}, {}, WallpaperArrangement::per, third));
    record("refresh.selected.kept",
           refresh_report(one_wallpaper, {primary, secondary}, {}, WallpaperArrangement::per,
                          secondary));

    // ---- UpdateWallpaperRect() ---------------------------------------------
    for (const auto arrangement : kArrangements) {
        const std::string tag = arrangement_name(arrangement);
        // One display, one wallpaper: the span branch needs >1 screen, so this must
        // take the per-screen path even for `span`.
        record("rect.single." + tag,
               core::describe_rect(core::plan_update_rect(
                   std::vector<WallpaperSlot>{{primary, "wp-a"}}, {primary}, arrangement)));
        record("rect.two." + tag,
               core::describe_rect(core::plan_update_rect(
                   {{primary, "wp-a"}, {secondary, "wp-b"}}, {primary, secondary}, arrangement)));
        // An orphan still in the list produces no update for its screen.
        record("rect.orphan." + tag,
               core::describe_rect(core::plan_update_rect({{primary, "wp-a"}, {third, "wp-c"}},
                                                          {primary}, arrangement)));
    }

    // A layout whose virtual screen has a negative origin: the rect is rebased.
    {
        const DisplayMonitor moved_primary = disp("P", -1920, -200, 1920, 1080, true);
        const DisplayMonitor moved_secondary = disp("S", 0, 0, 2560, 1440);
        const std::vector<WallpaperSlot> moved = {{moved_primary, "wp-a"}, {moved_secondary, "wp-b"}};
        const std::vector<DisplayMonitor> displays = {moved_primary, moved_secondary};
        record("rect.negative-origin.per",
               core::describe_rect(core::plan_update_rect(moved, displays, WallpaperArrangement::per)));
        record("rect.negative-origin.span",
               core::describe_rect(core::plan_update_rect(moved, displays, WallpaperArrangement::span)));
    }

    // ---- RestoreDisconnectedWallpapers() ------------------------------------
    for (const auto arrangement : kArrangements) {
        const std::vector<WallpaperSlot> wallpapers = {{primary, "wp-a"}};
        const std::vector<DisplayMonitor> displays = {primary, secondary, third};
        const std::vector<WallpaperLayoutModel> disconnected = {
            WallpaperLayoutModel(std::make_shared<DisplayMonitor>(secondary), "wp-b"),
            WallpaperLayoutModel(std::make_shared<DisplayMonitor>(disp("GONE", 5000, 0, 800, 600)),
                                 "wp-x"),
        };
        record("restoreDisconnected." + arrangement_name(arrangement),
               core::describe_restore_disconnected(core::plan_restore_disconnected(
                   wallpapers, displays, disconnected, arrangement)));
    }
    record("restoreDisconnected.duplicate.full",
           core::describe_restore_disconnected(core::plan_restore_disconnected(
               {{primary, "wp-a"}, {secondary, "wp-b"}}, {primary, secondary}, {},
               WallpaperArrangement::duplicate)));
    record("restoreDisconnected.duplicate.empty",
           core::describe_restore_disconnected(core::plan_restore_disconnected(
               {}, {primary, secondary}, {}, WallpaperArrangement::duplicate)));

    // ---- RestoreWallpaper(layout) -------------------------------------------
    const std::vector<DisplayMonitor> attached = {primary, secondary};
    const std::vector<DisplayMonitor> missing_screen = {primary, secondary};  // no `third`
    const auto always_readable = [](const std::string&) { return true; };

    // (a) sources ARE the queue's own entries (RestoreDisconnectedWallpapers).
    record("restoreApply.identity.missing",
           core::describe_restore_apply(core::plan_restore(
               {{WallpaperLayoutModel(std::make_shared<DisplayMonitor>(third), "wp-t"), 0}},
               missing_screen, {WallpaperLayoutModel(std::make_shared<DisplayMonitor>(third), "wp-t")},
               always_readable)));
    // (b) identical contents, no identity handle (the startup path): the
    //     reference-based Contains misses, so a duplicate is queued.
    record("restoreApply.fresh.missing",
           core::describe_restore_apply(core::plan_restore(
               {RestoreSource{WallpaperLayoutModel(std::make_shared<DisplayMonitor>(third), "wp-t"),
                              std::nullopt}},
               missing_screen, {WallpaperLayoutModel(std::make_shared<DisplayMonitor>(third), "wp-t")},
               always_readable)));
    // (c) screen connected, entry is the queue's own object: restored and removed.
    record("restoreApply.identity.connected",
           core::describe_restore_apply(core::plan_restore(
               {{WallpaperLayoutModel(std::make_shared<DisplayMonitor>(secondary), "wp-b"), 0}},
               attached,
               {WallpaperLayoutModel(std::make_shared<DisplayMonitor>(secondary), "wp-b")},
               always_readable)));
    // (d) screen connected but a fresh reference: restored, yet the stale queue
    //     entry survives because Remove compares references.
    record("restoreApply.fresh.connected",
           core::describe_restore_apply(core::plan_restore(
               {RestoreSource{WallpaperLayoutModel(std::make_shared<DisplayMonitor>(secondary), "wp-b"),
                              std::nullopt}},
               attached,
               {WallpaperLayoutModel(std::make_shared<DisplayMonitor>(secondary), "wp-b")},
               always_readable)));
    // (e) unreadable library directory: dropped from the queue.
    record("restoreApply.unreadable",
           core::describe_restore_apply(core::plan_restore(
               {{WallpaperLayoutModel(std::make_shared<DisplayMonitor>(secondary), "wp-bad"), 0}},
               attached,
               {WallpaperLayoutModel(std::make_shared<DisplayMonitor>(secondary), "wp-bad")},
               [](const std::string& path) { return path != "wp-bad"; })));

    // (f) a null Display is a DOCUMENTED DEVIATION, asserted separately below —
    //     the golden line records that the C# throws here.

    // ---- SaveWallpaperLayout() ---------------------------------------------
    for (const auto arrangement : kArrangements) {
        const std::vector<WallpaperSlot> wallpapers = {{primary, "wp-a"}, {secondary, "wp-b"}};
        const std::vector<WallpaperLayoutModel> disconnected = {
            WallpaperLayoutModel(std::make_shared<DisplayMonitor>(third), "wp-t")};
        const std::string tag = arrangement_name(arrangement);
        record("compose." + tag, core::describe_layout(core::compose_layout(wallpapers, disconnected, arrangement)));
        // Duplicate entries are not deduped.
        const std::vector<WallpaperLayoutModel> dupes = {
            WallpaperLayoutModel(std::make_shared<DisplayMonitor>(secondary), "wp-b"),
            WallpaperLayoutModel(std::make_shared<DisplayMonitor>(third), "wp-t"),
        };
        record("compose.dupes." + tag, core::describe_layout(core::compose_layout(wallpapers, dupes, arrangement)));
    }

    // ---- RestoreWallpaper() (the public, startup one) -----------------------
    {
        const std::vector<WallpaperLayoutModel> layout = {
            WallpaperLayoutModel(std::make_shared<DisplayMonitor>(primary), "wp-a"),
            WallpaperLayoutModel(std::make_shared<DisplayMonitor>(secondary), "wp-b"),
        };
        for (const auto arrangement : kArrangements) {
            record("startup." + arrangement_name(arrangement),
                   core::describe_startup_restore(
                       core::plan_startup_restore(layout, arrangement, primary)));
        }
        record("startup.empty.span",
               core::describe_startup_restore(
                   core::plan_startup_restore({}, WallpaperArrangement::span, primary)));
    }

    // ---- compare ------------------------------------------------------------
    std::size_t mismatches = 0;
    for (const auto& [key, value] : lines) {
        const std::string expected = golden_value(key);
        INFO("scenario: " << key);
        INFO("  csharp: " << expected);
        INFO("  c++   : " << value);
        if (expected != value) ++mismatches;
        CHECK(expected == value);
    }
    INFO("scenarios compared: " << lines.size());
    CHECK(mismatches == 0);

    // Both directions of coverage: a scenario with no fixture line would assert
    // nothing, and a fixture line with no scenario would let a rule regress
    // silently. `restoreApply.nullDisplay` is the one deliberate exception (the C#
    // throws; the port's gentler behaviour is asserted in its own test case).
    std::vector<std::string> fixture_keys;
    {
        const std::string fixture = read_file(kGoldensDir + "/desktop_layout_csharp.txt");
        REQUIRE_FALSE(fixture.empty());
        std::size_t pos = 0;
        while (pos < fixture.size()) {
            std::size_t end = fixture.find('\n', pos);
            if (end == std::string::npos) end = fixture.size();
            const std::string line = fixture.substr(pos, end - pos);
            const std::size_t tab = line.find('\t');
            if (tab != std::string::npos) fixture_keys.push_back(line.substr(0, tab));
            pos = end + 1;
        }
        REQUIRE_FALSE(fixture_keys.empty());
    }

    std::vector<std::string> recorded_keys;
    for (const auto& [key, value] : lines) recorded_keys.push_back(key);

    for (const auto& key : fixture_keys) {
        if (key == "restoreApply.nullDisplay") continue;
        INFO("fixture key not replayed: " << key);
        CHECK(std::find(recorded_keys.begin(), recorded_keys.end(), key) != recorded_keys.end());
    }
    for (const auto& key : recorded_keys) {
        INFO("scenario with no fixture line: " << key);
        CHECK(std::find(fixture_keys.begin(), fixture_keys.end(), key) != fixture_keys.end());
    }
    CHECK(fixture_keys.size() == recorded_keys.size() + 1);  // + nullDisplay
}

TEST_CASE("a layout entry with a null display is tolerated, unlike the C#",
          "[desktop][regression]") {
    // The golden records `restoreApply.nullDisplay -> threw:NullReferenceException`:
    // the C# evaluates `x.Equals(entry.Display)` with a null Display, so a
    // hand-edited layout file (or a pre-v1.9 one) crashes wallpaper restore.
    //
    // The port deliberately does not reproduce a crash. A null Display is treated
    // as "screen missing", which lands the entry in the disconnected queue instead
    // of aborting startup — the same path a genuinely unplugged screen takes.
    CHECK(golden_value("restoreApply.nullDisplay") == "threw:NullReferenceException");

    WallpaperLayoutModel no_display(nullptr, "wp-null");
    const auto plan = core::plan_restore(
        {RestoreSource{no_display, std::nullopt}}, {primary_display()}, {},
        [](const std::string&) { return true; });

    REQUIRE(plan.items.size() == 1);
    CHECK_FALSE(plan.items[0].screen.has_value());
    CHECK(plan.items[0].queued_to_disconnected);
    CHECK_FALSE(plan.items[0].restored);
    CHECK(plan.items.size() == 1);
    CHECK(plan.disconnected.size() == 1);
}

TEST_CASE("DeviceId is the only thing screen identity compares", "[desktop][regression]") {
    // Everything above depends on this: a monitor whose bounds changed (different
    // resolution, different position) is still "the same screen" because
    // DisplayMonitor.Equals compares DeviceId only.
    const DisplayMonitor a = disp("SAME", 0, 0, 1920, 1080);
    const DisplayMonitor b = disp("SAME", 1920, 0, 2560, 1440);
    const DisplayMonitor c = disp("OTHER", 0, 0, 1920, 1080);
    CHECK(models::same_display(a, b));
    CHECK_FALSE(models::same_display(a, c));

    // Consequence: a wallpaper on `a` is NOT an orphan when `b` is connected.
    const std::vector<WallpaperSlot> wallpapers = {{a, "wp"}};
    const RefreshPlan plan = core::plan_refresh(wallpapers, {b}, {}, WallpaperArrangement::per, b, b);
    CHECK(plan.orphans.empty());

    // But it IS an orphan when only a different id is present.
    const RefreshPlan orphaned =
        core::plan_refresh(wallpapers, {c}, {}, WallpaperArrangement::per, c, c);
    REQUIRE(orphaned.orphans.size() == 1);
    CHECK(orphaned.orphans[0].lively_info_path == "wp");
}

TEST_CASE("IsMultiScreen is a count, not a geometry test", "[desktop][regression]") {
    CHECK_FALSE(core::is_multi_screen({}));
    CHECK_FALSE(core::is_multi_screen({primary_display()}));
    CHECK(core::is_multi_screen({primary_display(), secondary_display()}));
    // A single monitor that is not at the origin is still single-screen — the span
    // branch of UpdateWallpaperRect must not engage, which is what the
    // `rect.single.span` golden line records.
    CHECK_FALSE(core::is_multi_screen({disp("P", -1920, 0, 1920, 1080, true)}));
}

TEST_CASE("virtual screen bounds union every display", "[desktop][regression]") {
    const models::Rectangle single = core::virtual_screen_bounds({disp("P", -1920, -200, 1920, 1080)});
    CHECK(single.x == -1920);
    CHECK(single.y == -200);
    CHECK(single.width == 1920);
    CHECK(single.height == 1080);

    const models::Rectangle two =
        core::virtual_screen_bounds({disp("P", -1920, -200, 1920, 1080), disp("S", 0, 0, 2560, 1440)});
    CHECK(two.x == -1920);
    CHECK(two.y == -200);
    CHECK(two.width == 4480);
    CHECK(two.height == 1640);
}
