// Wallpaper/screensaver layout files — WallpaperLayout.json and
// ScreenSaverLayout.json — replayed against the C# oracle
// (tests/goldens/layout_csharp.txt, generated by `csharp_probe layout`).
//
// The point of this fixture is the *nested* DisplayMonitor contract, which the
// settings fixture never exercised (its SelectedDisplay is null). Newtonsoft
// writes this class in a way nobody would guess:
//
//   * the public field `isStale` is serialized, and fields precede properties,
//     so it is the first member;
//   * System.Drawing.Rectangle has a TypeConverter, so Bounds/WorkingArea are
//     the *string* "x, y, width, height";
//   * IntPtr HMonitor becomes an object: {"value": <int>}.
//
// A port that inlines the "obvious" shape silently writes settings.json and
// layout files the C# app cannot read, so this fixture exists to make that
// failure loud.

#include <catch2/catch_test_macros.hpp>

#include <lively/common/json_util.h>
#include <lively/models/display_monitor.h>
#include <lively/models/settings_model.h>
#include <lively/models/wallpaper_layout.h>

#include <nlohmann/json.hpp>

#include <filesystem>
#include <fstream>
#include <memory>
#include <sstream>
#include <string>
#include <vector>

using namespace lively;
using models::DisplayMonitor;
using models::Rectangle;
using models::ScreenSaverLayoutModel;
using models::WallpaperArrangement;
using models::WallpaperLayoutModel;

namespace {

namespace fs = std::filesystem;

#ifdef LIVELY_GOLDENS_DIR
const std::string kGoldensDir = LIVELY_GOLDENS_DIR;
#else
const std::string kGoldensDir = "tests/goldens";
#endif

// The exact fixture the probe builds: two displays, one of them marked stale,
// one layout entry with a null path, and a screensaver list whose last entry has
// a null wallpaper list.
const char* kPrimaryDeviceId =
    "\\\\?\\DISPLAY#DEL41B9#5&2f0b1a4e&0&UID4352#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}";
const char* kSecondaryDeviceId = "\\\\?\\DISPLAY#GSM5B08#4&1a2b3c4d&0&UID256";

DisplayMonitor primary_display() {
    DisplayMonitor display;
    display.device_id = kPrimaryDeviceId;
    display.device_name = "\\\\.\\DISPLAY1";
    display.display_name = "Dell U2720Q";
    display.h_monitor = 0x10001;
    display.is_primary = true;
    display.index = 0;
    display.bounds = Rectangle{-1920, 0, 1920, 1080};
    display.working_area = Rectangle{-1920, 0, 1920, 1040};
    return display;
}

DisplayMonitor secondary_display() {
    DisplayMonitor display;
    display.device_id = kSecondaryDeviceId;
    display.device_name = "\\\\.\\DISPLAY2";
    display.display_name = "LG UltraGear";
    display.h_monitor = 0x20002;
    display.is_primary = false;
    display.index = 1;
    display.bounds = Rectangle{0, 0, 2560, 1440};
    display.working_area = Rectangle{0, 0, 2560, 1400};
    display.is_stale = true; // the public field, written first by Newtonsoft
    return display;
}

std::string escaped_payload(const std::string& payload) {
    std::string out;
    for (const char c : payload) {
        switch (c) {
        case '\\': out += "\\\\"; break;
        case '\n': out += "\\n"; break;
        case '\r': out += "\\r"; break;
        case '\t': out += "\\t"; break;
        case '"': out += "\\\""; break;
        default:
            if (static_cast<unsigned char>(c) < 0x20) {
                static const char* digits = "0123456789abcdef";
                out += "\\x";
                out.push_back(digits[(static_cast<unsigned char>(c) >> 4) & 0xF]);
                out.push_back(digits[static_cast<unsigned char>(c) & 0xF]);
            } else {
                out.push_back(c);
            }
        }
    }
    return out;
}

std::string read_file(const std::string& path) {
    std::ifstream in(path, std::ios::binary);
    std::stringstream ss;
    ss << in.rdbuf();
    return ss.str();
}

std::string scratch_dir() {
    return (fs::temp_directory_path() / "lively_layout_probe").string();
}

std::string g_report;

void line(const std::string& key, const std::string& value) {
    g_report += key;
    g_report += '\t';
    g_report += value;
    g_report += '\n';
}

std::string describe(const WallpaperLayoutModel& layout) {
    std::string display = "<null>";
    if (layout.display) {
        display = layout.display->device_id + "|" + std::to_string(layout.display->index);
    }
    return "livelyinfopath=" +
           (layout.lively_info_path.has_value() ? "[" + *layout.lively_info_path + "]" : "<null>") +
           ";display=" + display;
}

std::string canonical_report() {
    g_report.clear();
    std::error_code ec;
    fs::remove_all(scratch_dir(), ec);
    fs::create_directories(scratch_dir(), ec);

    const DisplayMonitor primary = primary_display();
    const DisplayMonitor secondary = secondary_display();

    // JsonConvert.SerializeObject(display) — compact, no indentation.
    line("display.serialize.plain", escaped_payload(models::display_to_json(primary).dump()));
    line("display.serialize.stale", escaped_payload(models::display_to_json(secondary).dump()));

    std::vector<WallpaperLayoutModel> wallpapers;
    wallpapers.emplace_back(std::make_shared<DisplayMonitor>(primary), "C:\\wallpapers\\one");
    wallpapers.emplace_back(std::make_shared<DisplayMonitor>(secondary), std::nullopt);

    const std::string wallpaper_path =
        (fs::path(scratch_dir()) / "WallpaperLayout.json").string();
    common::JsonStorage::StoreWallpaperLayoutData(wallpaper_path, wallpapers);
    line("wallpaperlayout.serialize", escaped_payload(read_file(wallpaper_path)));

    const auto reloaded = common::JsonStorage::LoadWallpaperLayoutData(wallpaper_path);
    for (std::size_t i = 0; i < reloaded.size(); ++i) {
        line("wallpaperlayout.reloaded." + std::to_string(i), describe(reloaded[i]));
    }

    std::vector<ScreenSaverLayoutModel> screen_saver;
    ScreenSaverLayoutModel per;
    per.layout = WallpaperArrangement::per;
    per.wallpapers = std::vector<WallpaperLayoutModel>{WallpaperLayoutModel(
        std::make_shared<DisplayMonitor>(primary), "C:\\wallpapers\\one")};
    screen_saver.push_back(per);

    ScreenSaverLayoutModel span;
    span.layout = WallpaperArrangement::span;
    span.wallpapers = std::vector<WallpaperLayoutModel>{
        WallpaperLayoutModel(std::make_shared<DisplayMonitor>(primary), "C:\\wallpapers\\two"),
        WallpaperLayoutModel(std::make_shared<DisplayMonitor>(secondary), "C:\\wallpapers\\three")};
    screen_saver.push_back(span);

    ScreenSaverLayoutModel duplicate;
    duplicate.layout = WallpaperArrangement::duplicate;
    duplicate.wallpapers = std::nullopt;
    screen_saver.push_back(duplicate);

    const std::string screensaver_path =
        (fs::path(scratch_dir()) / "ScreenSaverLayout.json").string();
    common::JsonStorage::StoreScreenSaverLayoutData(screensaver_path, screen_saver);
    line("screensaverlayout.serialize", escaped_payload(read_file(screensaver_path)));

    // DisplayMonitor.Equals compares DeviceId only.
    DisplayMonitor same_id;
    same_id.device_id = primary.device_id;
    same_id.device_name = "\\\\.\\DISPLAY9";
    DisplayMonitor other_id;
    other_id.device_id = "different";
    line("display.equals.same-id", models::same_display(primary, same_id) ? "true" : "false");
    line("display.equals.other-id", models::same_display(primary, other_id) ? "true" : "false");
    line("display.equals.self", models::same_display(primary, primary) ? "true" : "false");

    return g_report;
}

std::vector<std::string> split_lines(const std::string& text) {
    std::vector<std::string> out;
    std::string current;
    for (const char c : text) {
        if (c == '\n') {
            if (!current.empty() && current.back() == '\r') current.pop_back();
            out.push_back(current);
            current.clear();
        } else {
            current.push_back(c);
        }
    }
    if (!current.empty()) out.push_back(current);
    return out;
}

} // namespace

TEST_CASE("layout files match the C# oracle", "[layout][oracle]") {
    const std::string expected_text = read_file(kGoldensDir + "/layout_csharp.txt");
    REQUIRE_FALSE(expected_text.empty());

    const auto expected = split_lines(expected_text);
    const auto actual = split_lines(canonical_report());

    std::size_t mismatches = 0;
    const std::size_t compared = std::min(expected.size(), actual.size());
    for (std::size_t i = 0; i < compared; ++i) {
        if (expected[i] == actual[i]) continue;
        if (++mismatches <= 12) {
            INFO("line " << i + 1);
            INFO("  csharp: " << expected[i]);
            INFO("  c++   : " << actual[i]);
        }
        CHECK(expected[i] == actual[i]);
    }
    INFO("csharp lines: " << expected.size() << ", c++ lines: " << actual.size());
    CHECK(expected.size() == actual.size());
}

TEST_CASE("settings.json keeps a nested display readable by the C# app",
          "[layout][settings][regression]") {
    // The shape this fixture was written for: a DisplayMonitor inside another
    // model must round-trip every member, including the ones Newtonsoft writes
    // in non-obvious forms.
    models::SettingsModel settings;
    settings.selected_display = std::make_shared<DisplayMonitor>(secondary_display());
    settings.selected_audio_output_display = std::make_shared<DisplayMonitor>(primary_display());

    const std::string json = settings.to_json_string();
    const auto parsed = nlohmann::ordered_json::parse(json);
    const auto& display = parsed.at("SelectedDisplay");
    CHECK(display.at("isStale").get<bool>());
    CHECK(display.at("Bounds").get<std::string>() == "0, 0, 2560, 1440");
    CHECK(display.at("WorkingArea").get<std::string>() == "0, 0, 2560, 1400");
    CHECK(display.at("HMonitor").at("value").get<std::int64_t>() == 0x20002);
    CHECK(display.at("DeviceId").get<std::string>() == kSecondaryDeviceId);

    const models::SettingsModel round_tripped = models::SettingsModel::from_json_string(json);
    REQUIRE(round_tripped.selected_display != nullptr);
    CHECK(round_tripped.selected_display->device_id == kSecondaryDeviceId);
    CHECK(round_tripped.selected_display->is_stale);
    CHECK(round_tripped.selected_display->h_monitor == 0x20002);
    CHECK(round_tripped.selected_display->bounds.width == 2560);
    CHECK(round_tripped.selected_display->working_area.height == 1400);
    REQUIRE(round_tripped.selected_audio_output_display != nullptr);
    CHECK(round_tripped.selected_audio_output_display->index == 0);
}

TEST_CASE("layout models tolerate absent optional members", "[layout]") {
    // A hand-written or older file: no LivelyScreen, no LivelyInfoPath.
    const auto layout = WallpaperLayoutModel::from_json(nlohmann::ordered_json::object());
    CHECK(layout.display == nullptr);
    CHECK(layout.lively_info_path == std::nullopt);

    const auto screen_saver =
        ScreenSaverLayoutModel::from_json(nlohmann::ordered_json::object());
    CHECK(screen_saver.layout == WallpaperArrangement::per);
    CHECK(screen_saver.wallpapers == std::nullopt);

    // An empty list stays an empty list rather than becoming null.
    const auto empty = ScreenSaverLayoutModel::from_json(
        nlohmann::ordered_json{{"Layout", 1}, {"Wallpapers", nlohmann::ordered_json::array()}});
    REQUIRE(empty.wallpapers.has_value());
    CHECK(empty.wallpapers->empty());

    // Rectangle parsing tolerates padding and truncation.
    CHECK(models::rectangle_from_string(" 1,2 , 3,4 ").width == 3);
    CHECK(models::rectangle_from_string("5").x == 5);
    CHECK(models::rectangle_from_string("").x == 0);
    CHECK(models::rectangle_to_string(Rectangle{-1, 2, 3, 4}) == "-1, 2, 3, 4");
}
